- hosts: kube
  gather_facts: no
  become: yes
  tasks:
   - name: install Docker
     yum:
       name: docker
       state: present
       update_cache: true

   - name: start Docker
     systemd:
       name: docker
       state: started
       enabled: yes

#   - name: disable SELinux
#     command: setenforce 0

   - name: disable SELinux on reboot
     selinux:
       state: disabled

   - name: ensure net.bridge.bridge-nf-call-ip6tables is set to 1
     sysctl:
      name: net.bridge.bridge-nf-call-ip6tables
      value: 1
      state: present

   - name: ensure net.bridge.bridge-nf-call-iptables is set to 1
     sysctl:
      name: net.bridge.bridge-nf-call-iptables
      value: 1
      state: present

   - name: ensure net.bridge.bridge-nf-call-arptables is set to 1
     sysctl:
      name: net.bridge.bridge-nf-call-arptables
      value: 1
      state: present

   - name: disable swap
     shell: swapoff -a 

   - name: disable swap
     replace:  
       path: /etc/fstab
       regexp: '^(.+?\sswap\s+sw\s+.*)$'
       replace: '# \1'

   - name: add Kubernetes' YUM repository
     yum_repository:
      name: Kubernetes
      description: Kubernetes YUM repository
      baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
      gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
      gpgcheck: yes

   - name: install kubelet
     yum:
        name: kubelet-1.15.0
        state: present
        update_cache: true
     tags:
       - kube

   - name: install kubeadm
     yum:
        name: kubeadm-1.15.0
        state: present
     tags:
       - kube

   - name: start kubelet
     service:
       name: kubelet
       enabled: yes
       state: started
     tags:
       - kube

- hosts: kubem
  become: yes
  tasks:
   - name: install kubectl
     yum:
        name: kubectl-1.15.0
        state: present
        allow_downgrade: yes
     tags:
       - kube

